bookmark/urls.py
from django.urls import path
from .views import BookmarkList, BookmarkDetail, BookmarkCreate, BookmarkUpdate, BookmarkDelete


app_name = 'bookmark'

urlpatterns = [
    path('', BookmarkList.as_view(), name='index'),
    path('detail/<pk>/', BookmarkDetail.as_view(), name='detail'),
    path('create/', BookmarkCreate.as_view(), name='create'),
    path('update/<pk>/', BookmarkUpdate.as_view(), name='update'),
    path('delete/<pk>/', BookmarkDelete.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookmark.urls')),
]

bookmark/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Bookmark(models.Model):
    site_name = models.CharField(max_length=50)
    url = models.URLField()
    contents = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Site name : " +self.site_name+", URL : " +self.url


    class Meta:
        ordering = ['site_name']

bookmark/views.py
from django.shortcuts import render

# Create your views here.

from .models import Bookmark

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import redirect
from django.urls import reverse_lazy

class BookmarkList(ListView):
    model = Bookmark

class BookmarkDetail(DetailView):
    model = Bookmark

class BookmarkCreate(CreateView):
    model = Bookmark
    fields = ['site_name', 'url', 'contents']
    template_name_suffix = '_create'
    success_url = '/'

class BookmarkUpdate(UpdateView):
    model = Bookmark
    fields = ['site_name', 'url', 'contents']
    template_name_suffix = '_update'
    success_url = '/'
    #success_url = '/update/{pk}/'


class BookmarkDelete(DeleteView):
    model = Bookmark
    template_name_suffix = '_delete'
    success_url = '/'

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}
{% block title %}
Add Bookmark
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8">
        <div class="alert alert-info" role="alert">
            Please insert bookmark information.
        </div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_delete.html
{% extends 'base.html' %}
{% block title %}
Delete Bookmark
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8">
        <div class="alert alert-danger" role="alert">
            Do you want to delete {{object}}?
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Delete Ok">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}
{% block title %}
Bookmark Detail
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8">
        <div class="card" >
            <div class="card-body">
                <h5 class="card-title">{{object.site_name}}</h5>
                <h6 class="card-subtitle mb-2 text-muted"><a href="{{object.url}}">{{object.url}}</a></h6>
                <p class="card-text">{{object.contents}}</p>
                <a href="{% url 'bookmark:update' object.id %}" class="card-link btn btn-outline-warning">수정</a>
                <a href="{% url 'bookmark:delete' object.id %}" class="card-link btn btn-outline-danger">삭제</a>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block title %}
Bookmark List
{% endblock %}


{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-4">
        <a href="{% url 'bookmark:create' %}" class="btn btn-success" style="margin-bottom:1em;">Add Bookmark</a>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Site Name</th>
                    <th scope="col">Link</th>
                    <th scope="col">수정</th>
                    <th scope="col">삭제</th>
                </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{object.id}}</td>
                <td>
                    <a href="{% url 'bookmark:detail' object.id %}"> {{object.site_name}}</a>
                </td>
                <td><a href="{{object.url}}" target="_blank">링크 이동</a></td>
                <td><a href="{% url 'bookmark:update' object.id%}" class="btn btn-outline-warning">M</a></td>
                <td><a href="{% url 'bookmark:delete' object.id%}" class="btn btn-outline-danger">D</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}
{% block title %}
Update Bookmark
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8">
        <div class="alert alert-info" role="alert">
            Please change bookmark information.
        </div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Update">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}